name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
    - name: Install npm dependencies
      run: |
        cd app/ && npm install
    - name: Build app
      env:
        CI: false
      run: |
        cd app/ && npm run-script build
        mv build ../rld/app
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Build package
      run: |
        poetry build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist/
